# Generated by Django 3.2.12 on 2022-04-24 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qg', '0002_newuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newuser',
            old_name='first_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='about_you',
        ),
        migrations.RemoveField(
            model_name='newuser',
            name='last_name',
        ),
    ]
